"""chat

Revision ID: e3b72ab1144a
Revises: 3f0d7c7e1c4b
Create Date: 2026-04-25 18:05:25.664853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3b72ab1144a'
down_revision: Union[str, Sequence[str], None] = '3f0d7c7e1c4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_members',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_members_chat_id', 'chat_members', ['chat_id'], unique=False)
    op.create_index('ix_chat_members_user_id', 'chat_members', ['user_id'], unique=False)
    op.create_index('ux_chat_members_chat_user', 'chat_members', ['chat_id', 'user_id'], unique=True)
    op.create_table('messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Enum('TEXT', 'AUDIO', name='message_type'), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('audio_key', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_chat_id', 'messages', ['chat_id'], unique=False)
    op.create_index('ix_messages_created_at', 'messages', ['created_at'], unique=False)
    op.add_column('track_lists', sa.Column('image_filename', sa.String(length=255), nullable=True))
    op.add_column('tracks', sa.Column('audio_key', sa.String(length=512), nullable=True))
    op.drop_index(op.f('ix_tracks_track_lists_track_list_id_position'), table_name='tracks_track_lists')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tracks_track_lists_track_list_id_position'), 'tracks_track_lists', ['track_list_id', 'position'], unique=False)
    op.drop_column('tracks', 'audio_key')
    op.drop_column('track_lists', 'image_filename')
    op.drop_index('ix_messages_created_at', table_name='messages')
    op.drop_index('ix_messages_chat_id', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ux_chat_members_chat_user', table_name='chat_members')
    op.drop_index('ix_chat_members_user_id', table_name='chat_members')
    op.drop_index('ix_chat_members_chat_id', table_name='chat_members')
    op.drop_table('chat_members')
    op.drop_table('chats')
    # ### end Alembic commands ###
